### ISSUE TITLE
Password input in Login Screen UI

### ISSUE THREAD

**Issue by SlayerAnsh** [anshukaira/insta-clone#14]
Password input UI in Login screen can be improved. Take inspiration from email input and implement similar ui for password input.

Issue:
- Password input is not full width and height ( view email input for desired behavior)
- Because its not full width and height, we need to click on specific area to activate password input
- Because its not full width and height, border on focus is not is not looking good

Solution Hint:
- Make input full width and height and place the eye icon using position: absolute.

**Comment by hendaoui** [comment]
@SlayerAnsh I'd like to work on it!
